name: Another Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Log Hello World To Console
        run: echo "Hello world"
        shell: bash

      - name: Run All Tests
        run: echo "Hello Tests"
        shell: bash

  goodbye_world:
    runs-on: ubuntu-latest
    steps:
      - name: Log Goodbye World to Console
        run: echo "Goodbye world"
        shell: bash
## write workflows for the following events - push to a branch, pull request opened to a branch, pull request close for a branch, issue creation, forks on a branch
