# name: Cron Workflow
# on:
#   schedule:
#     - cron: "*/5 * * * *"

# jobs:
#   print-log:
#     runs-on: ubuntu-latest
#     steps:
#       - name: print the log
#         run: echo the cron workflow was triggered
