name: Hello World Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #pulls the code that triggers this workflow into the runner
      - name: hello world
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo 'goodbye world'
        shell: bash

  matrixJob:
    strategy:
      matrix:
        version: [1, 2, 3]
    runs-on: ubuntu-latest
    steps:
      - name: Should use matrix array
        run: echo "version ${{ matrix.version }}"
        shell: bash
