name: Pull Request Closed

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Print PR was merged to console
        run: |
          echo The PR was merged

  if_not_merged:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Print PR status
        run: echo The PR was not merged
